spring:
  datasource:
    url: jdbc:mysql://localhost:8080/OrdersDataBase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: OrderDB
    password: 0123456789
hibernate:
  ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file: logs/application.log